(() => {
  const accessed = "2026-05-01";

  const search = {
    googleMaps: (q) => `https://www.google.com/maps/search/${encodeURIComponent(q)}`,
    xhs: (q) => `https://www.xiaohongshu.com/search_result?keyword=${encodeURIComponent(q)}`,
    agoda: (q) => `https://www.agoda.com/search?city=${encodeURIComponent(q)}`,
    commons: (q) => `https://commons.wikimedia.org/w/index.php?search=${encodeURIComponent(q)}&title=Special:MediaSearch&type=image`,
    local: (path) => path,
  };

  const source = (sourceName, sourceUrl, pending = false) => ({
    sourceName,
    sourceUrl,
    dateAccessed: accessed,
    pending,
  });

  const assetPlace = (id) => `./assets/places/${id}.svg`;
  const assetCover = (name) => `./assets/covers/${name}`;

  const continents = [
    { id: "all", label: "全部", bounds: [[-48, -130], [68, 150]], center: [22, 40], zoom: 2 },
    { id: "亚洲", label: "亚洲", bounds: [[5, 72], [46, 143]], center: [29, 111], zoom: 4 },
    { id: "欧洲", label: "欧洲", bounds: [[35, -12], [66, 32]], center: [49, 9], zoom: 4 },
    { id: "北美洲", label: "北美", bounds: [[15, -130], [50, -65]], center: [36, -102], zoom: 4 },
    { id: "南美洲", label: "南美", bounds: [[-40, -82], [12, -35]], center: [-15, -62], zoom: 4 },
    { id: "欧亚", label: "欧亚", bounds: [[30, 25], [43, 45]], center: [39, 33], zoom: 5 },
    { id: "意象", label: "意象", bounds: [[12, -12], [34, 38]], center: [25, 10], zoom: 4 },
  ];

  const descriptions = {
    eat: "餐饮入口来自公开地图与旅行内容检索，适合作为到达后的第一餐候选。",
    stay: "住宿入口优先给出公开预订与旅行攻略检索，打开来源后请按实时评分、评价人数与位置再筛选。",
    move: "行程节点可在局部地图中串联，适合拍照、转乘或理解城市动线。",
    shop: "购物与纪念品节点偏向书店、市场、明信片、唱片或当地手作。",
  };

  const typeNames = { eat: "吃", stay: "住", move: "行", shop: "购物" };

  function recommendation(kind, name, destination, lat, lng, index) {
    const query = `${destination} ${name}`;
    const sourceInfo =
      kind === "stay"
        ? source("Agoda 住宿公开检索", search.agoda(query))
        : index === 1
          ? source("小红书公开检索", search.xhs(`${query} 攻略`))
          : source("Google Maps 公开检索", search.googleMaps(query));

    return {
      name,
      type: typeNames[kind],
      description: descriptions[kind],
      lat: Number((lat + (index - 0.5) * 0.018).toFixed(5)),
      lng: Number((lng + (index - 0.5) * 0.018).toFixed(5)),
      verification: "请打开来源核验实时评分、评价人数、营业状态与最新价格；原型不伪造实时评分。",
      source: sourceInfo,
    };
  }

  const destinationRows = [
    {
      id: "paris",
      name: "巴黎",
      displayName: "巴黎（法国）",
      continent: "欧洲",
      lat: 48.8567,
      lng: 2.3508,
      songs: ["旅行的意义", "Pussy"],
      lyricLines: ["你品尝了夜的巴黎"],
      intro: "塞纳河、铁塔、咖啡馆与夜色构成这张地图里最适合被做成明信片的巴黎。",
      eat: ["Le Relais de l'Entrecote", "Du Pain et des Idees"],
      stay: ["The People Paris Marais", "Hotel des Grandes Ecoles"],
      move: ["埃菲尔铁塔", "塞纳河游船"],
      shop: ["莎士比亚书店", "圣日耳曼德佩"],
    },
    {
      id: "beijing",
      name: "北京",
      displayName: "北京（中国）",
      continent: "亚洲",
      lat: 39.9056,
      lng: 116.3914,
      songs: ["旅行的意义"],
      lyricLines: ["你踏过下雪的北京"],
      intro: "北京以雪天、红墙、胡同与热茶呈现，更贴近歌词里的冬日脚印。",
      eat: ["四季民福烤鸭店", "南门涮肉"],
      stay: ["北京前门文华东方", "东四胡同民宿"],
      move: ["故宫角楼", "景山公园"],
      shop: ["南锣鼓巷", "五道营胡同"],
    },
    {
      id: "okinawa",
      name: "冲绳",
      displayName: "岛屿（冲绳，日本）",
      continent: "亚洲",
      lat: 26.2125,
      lng: 127.6792,
      songs: ["旅行的意义"],
      lyricLines: ["你拥抱热情的岛屿"],
      intro: "冲绳改为热情岛屿与海岸风格：蓝洞、美国村、海风与夏日公路。",
      eat: ["A&W Okinawa", "第一牧志公设市场"],
      stay: ["La'gent Hotel Okinawa Chatan", "Okinawa Guest House Grand Naha"],
      move: ["美国村", "青之洞窟"],
      shop: ["壶屋陶器街", "Umikaji Terrace"],
    },
    {
      id: "turkey",
      name: "土耳其",
      displayName: "土耳其",
      continent: "欧亚",
      lat: 39.9334,
      lng: 32.8597,
      songs: ["旅行的意义"],
      lyricLines: ["你埋葬记忆的土耳其"],
      intro: "歌词里的土耳其像一枚记忆邮戳，页面以伊斯坦布尔与安卡拉作为可旅行坐标。",
      eat: ["Hafiz Mustafa", "Sultanahmet Koftecisi"],
      stay: ["Cheers Hostel Istanbul", "Hotel Amira Istanbul"],
      move: ["蓝色清真寺", "博斯普鲁斯海峡"],
      shop: ["大巴扎", "香料市场"],
    },
    {
      id: "shanghai",
      name: "上海",
      displayName: "上海（中国）",
      continent: "亚洲",
      lat: 31.2303,
      lng: 121.4736,
      songs: ["我喜欢上你时的内心活动"],
      lyricLines: ["上海的街道 雪山在边上"],
      intro: "上海是街道、咖啡、橱窗与电影感的组合，适合做城市漫游手账。",
      eat: ["佳家汤包", "% Arabica 武康路"],
      stay: ["上海衡山马勒别墅饭店", "大隐国际青年旅舍"],
      move: ["武康路", "外滩"],
      shop: ["安福路", "茑屋书店"],
    },
    {
      id: "geneva-lake",
      name: "日内瓦湖",
      displayName: "日内瓦湖（瑞士）",
      continent: "欧洲",
      lat: 46.2044,
      lng: 6.1432,
      songs: ["我喜欢上你时的内心活动"],
      lyricLines: ["你看那九点钟方向 日内瓦湖的房子贵吗"],
      intro: "日内瓦湖以湖面、喷泉和阿尔卑斯远景呈现，贴合歌词里的房子与湖。",
      eat: ["Bains des Paquis", "Chez Ma Cousine"],
      stay: ["Hotel Suisse Geneva", "City Hostel Geneva"],
      move: ["日内瓦湖喷泉", "花钟"],
      shop: ["Rue du Rhone", "Manor Geneve"],
    },
    {
      id: "qinghai",
      name: "青海",
      displayName: "青海（中国）",
      continent: "亚洲",
      lat: 36.6171,
      lng: 101.7782,
      songs: ["我喜欢上你时的内心活动"],
      lyricLines: ["你喜欢去哪 青海或三亚"],
      intro: "青海以湖、盐、风和高原光线为主，适合缓慢而开阔的旅行路线。",
      eat: ["益鑫羊肉手抓馆", "德禄酸奶"],
      stay: ["西宁新华联索菲特", "青海湖黑马河客栈"],
      move: ["青海湖", "茶卡盐湖"],
      shop: ["莫家街", "水井巷"],
    },
    {
      id: "sanya",
      name: "三亚",
      displayName: "三亚（海南，中国）",
      continent: "亚洲",
      lat: 18.2528,
      lng: 109.5119,
      songs: ["我喜欢上你时的内心活动"],
      lyricLines: ["你喜欢去哪 青海或三亚"],
      intro: "三亚保留海边胶片感：椰子、落日、免税店和湿热的夏天。",
      eat: ["嗲嗲的椰子鸡", "阿浪海鲜"],
      stay: ["三亚艾迪逊酒店", "三亚湾青旅"],
      move: ["椰梦长廊", "亚龙湾"],
      shop: ["三亚国际免税城", "第一市场"],
    },
    {
      id: "iceland",
      name: "冰岛",
      displayName: "冰岛",
      continent: "欧洲",
      lat: 64.1466,
      lng: -21.9426,
      songs: ["我喜欢上你时的内心活动"],
      lyricLines: ["冰岛或希腊 南美不去吗"],
      intro: "冰岛是极光、瀑布、苔原和温泉的组合，适合冷色调旅行手账。",
      eat: ["Baejarins Beztu Pylsur", "Cafe Loki"],
      stay: ["Kex Hostel Reykjavik", "Fosshotel Glacier Lagoon"],
      move: ["黄金圈", "蓝湖温泉"],
      shop: ["Laugavegur 购物街", "Kolaportid 跳蚤市场"],
    },
    {
      id: "greece",
      name: "希腊",
      displayName: "希腊",
      continent: "欧洲",
      lat: 37.9838,
      lng: 23.7275,
      songs: ["我喜欢上你时的内心活动"],
      lyricLines: ["冰岛或希腊 南美不去吗"],
      intro: "希腊以蓝白海岛和雅典古迹承接歌词里的远方选择题。",
      eat: ["O Thanasis Athens", "Kostas Souvlaki"],
      stay: ["City Circus Athens", "Santorini Hostel"],
      move: ["雅典卫城", "普拉卡"],
      shop: ["Monastiraki 跳蚤市场", "Ermou Street"],
    },
    {
      id: "south-america",
      name: "南美",
      displayName: "南美（歌词意象）",
      continent: "南美洲",
      lat: -13.1631,
      lng: -72.545,
      songs: ["我喜欢上你时的内心活动"],
      lyricLines: ["冰岛或希腊 南美不去吗"],
      intro: "南美作为歌词意象，暂以库斯科与马丘比丘代表安第斯山脉的旅行想象。",
      isConceptPlace: true,
      eat: ["Central Restaurante Lima", "San Pedro Market"],
      stay: ["Pariwana Hostel Cusco", "Tierra Viva Cusco"],
      move: ["马丘比丘", "库斯科圣谷"],
      shop: ["圣佩德罗市场", "羊驼织物店"],
    },
    {
      id: "desert",
      name: "沙漠",
      displayName: "沙漠（歌词意象）",
      continent: "意象",
      lat: 31.0456,
      lng: -7.1295,
      songs: ["我喜欢上你时的内心活动"],
      lyricLines: ["沙漠你爱吗"],
      intro: "沙漠作为歌词意象，选择摩洛哥撒哈拉营地路线作为可执行代表。",
      isConceptPlace: true,
      eat: ["Cafe Clock Marrakech", "Nomad Marrakech"],
      stay: ["Riad BE Marrakech", "Sahara Desert Luxury Camp"],
      move: ["马拉喀什", "Merzouga 沙丘"],
      shop: ["马拉喀什市集", "香料广场"],
    },
    {
      id: "highway-one",
      name: "一号公路",
      displayName: "一号公路（加州，美国）",
      continent: "北美洲",
      lat: 36.2704,
      lng: -121.8081,
      songs: ["我喜欢上你时的内心活动"],
      lyricLines: ["知道吗 今天的消息 说一号公路上 那座桥断了"],
      intro: "一号公路改为海岸公路、断崖和车窗视角，让页面更像公路片。",
      eat: ["Nepenthe Big Sur", "Big Sur Bakery"],
      stay: ["HI Monterey Hostel", "Carmel Mission Inn"],
      move: ["Bixby Creek Bridge", "Big Sur"],
      shop: ["Carmel Plaza", "Monterey Cannery Row"],
    },
    {
      id: "jiufen",
      name: "九份",
      displayName: "九份（台湾，中国）",
      continent: "亚洲",
      lat: 25.1097,
      lng: 121.8451,
      songs: ["九份的咖啡店"],
      lyricLines: ["这样的午后我坐在九份的马路边", "这样的午夜我坐在九份的咖啡店"],
      intro: "九份以山城、茶楼、夜色和咖啡店呈现，回到歌曲里的九份。",
      eat: ["阿妹茶楼", "赖阿婆芋圆"],
      stay: ["九份山经民宿", "九份老街民宿"],
      move: ["九份老街", "瑞芳车站"],
      shop: ["九份茶具店", "老街明信片"],
    },
    {
      id: "shonan",
      name: "湘南海岸",
      displayName: "湘南海岸（镰仓，日本）",
      continent: "亚洲",
      lat: 35.3189,
      lng: 139.55,
      songs: ["坐火车到传说中的湘南海岸"],
      lyricLines: ["坐火车到传说中的湘南海岸"],
      intro: "湘南改成海边、江之电、铁路与浪花风格，更符合坐火车去海岸的歌词。",
      eat: ["Bills Shichirigahama", "镰仓小町通小吃"],
      stay: ["Kamakura Guesthouse", "WeBase Kamakura"],
      move: ["镰仓高校前", "江之岛"],
      shop: ["小町通", "江之岛商店街"],
    },
    {
      id: "taipei",
      name: "台北",
      displayName: "台北（台湾，中国）",
      continent: "亚洲",
      lat: 25.032,
      lng: 121.5654,
      songs: ["台北某个地方"],
      lyricLines: ["有人在吗 台北的某个地方 为何听不见你的回答"],
      intro: "台北是城市回声：捷运、咖啡、书店、夜市和某个等待回答的地方。",
      eat: ["永康牛肉面", "宁夏夜市"],
      stay: ["Star Hostel Taipei Main Station", "中山民宿"],
      move: ["大安森林公园", "淡水河岸"],
      shop: ["诚品生活南西", "华山1914"],
    },
    {
      id: "havana",
      name: "哈瓦那",
      displayName: "哈瓦那（古巴）",
      continent: "北美洲",
      lat: 23.1136,
      lng: -82.3666,
      songs: ["背对哈瓦那"],
      lyricLines: ["背对哈瓦那"],
      intro: "哈瓦那以老爷车、海滨大道和摄影集气质为主，适合做书封式页面。",
      eat: ["La Guarida Havana", "El Floridita"],
      stay: ["Hostal Valencia Havana", "Hotel Nacional de Cuba"],
      move: ["哈瓦那老城", "马雷贡海滨大道"],
      shop: ["古巴海报店", "手作唱片摊"],
    },
    {
      id: "harbin",
      name: "哈尔滨",
      displayName: "哈尔滨（黑龙江，中国）",
      continent: "亚洲",
      lat: 45.8038,
      lng: 126.5349,
      songs: ["失败者的飞翔"],
      lyricLines: ["失败者的飞翔是在哈尔滨的一家饭店写完的"],
      intro: "哈尔滨用冬天、饭店、俄式建筑和《失败者的飞翔》形成城市章节。",
      eat: ["老厨家锅包肉", "马迭尔冷饮厅"],
      stay: ["哈尔滨中央大街马迭尔宾馆", "哈尔滨青旅"],
      move: ["中央大街", "圣索菲亚教堂"],
      shop: ["秋林里道斯", "中央书店"],
    },
    {
      id: "norway",
      name: "挪威",
      displayName: "挪威",
      continent: "欧洲",
      lat: 59.9139,
      lng: 10.7522,
      songs: ["Groupies 吉他手"],
      lyricLines: ["有千百种可能无解答 你去挪威找鱼算账"],
      intro: "挪威换成峡湾、渔村和冷色海岸，贴合歌词里的鱼与远方。",
      eat: ["Fiskeriet Youngstorget", "Mathallen Oslo"],
      stay: ["Anker Hostel Oslo", "Citybox Bergen"],
      move: ["奥斯陆峡湾", "卑尔根布吕根"],
      shop: ["Aker Brygge", "Bryggen 商店"],
    },
    {
      id: "uk",
      name: "英国",
      displayName: "英国",
      continent: "欧洲",
      lat: 51.5075,
      lng: -0.1277,
      songs: ["下个星期去英国"],
      lyricLines: ["oh 你收了行李 下个星期要去英国"],
      intro: "英国章节保留收拾行李的感觉：书店、地铁、剧院、唱片和雨天街道。",
      eat: ["Dishoom Covent Garden", "Borough Market"],
      stay: ["YHA London Central", "The Hoxton Shoreditch"],
      move: ["大英博物馆", "伦敦地铁"],
      shop: ["Daunt Books", "Rough Trade East"],
    },
  ];

  function buildDestination(row, index) {
    const recs = {
      eat: row.eat.map((name, i) => recommendation("eat", name, row.displayName, row.lat, row.lng, i)),
      stay: row.stay.map((name, i) => recommendation("stay", name, row.displayName, row.lat, row.lng, i)),
      move: row.move.map((name, i) => recommendation("move", name, row.displayName, row.lat, row.lng, i)),
      shop: row.shop.map((name, i) => recommendation("shop", name, row.displayName, row.lat, row.lng, i)),
    };
    const mapPins = Object.entries(recs).flatMap(([kind, items]) =>
      items.map((item) => ({
        kind,
        name: item.name,
        lat: item.lat,
        lng: item.lng,
        sourceUrl: item.source.sourceUrl,
      }))
    );
    const imageCredit = source(
      "本地旅行手账插画素材（可替换为 Bing 往期壁纸 / 免费图库 / AI 歌词意境图）",
      "./assets/sources.json",
      false
    );

    return {
      ...row,
      order: index + 1,
      heroImage: assetPlace(row.id),
      postcardImage: assetPlace(row.id),
      gallery: [assetPlace(row.id)],
      imageCredit,
      recommendations: recs,
      mapPins,
      route: [
        `抵达 ${row.name}，先确认交通方式与天气。`,
        `前往 ${row.move[0]}，拍下第一张旅行明信片。`,
        `在 ${row.eat[0]} 或附近餐饮点休息。`,
        `到 ${row.shop[0]} 挑选书信、唱片、纪念品或明信片。`,
        "整理照片、歌词与旅行感受，生成个人明信片。",
      ],
      sources: [
        imageCredit,
        source("Google Maps 目的地公开检索", search.googleMaps(row.displayName)),
        source("小红书旅行攻略公开检索", search.xhs(`${row.displayName} 旅行 攻略 吃住行 购物`)),
        source("Agoda 住宿公开检索", search.agoda(row.displayName)),
      ],
    };
  }

  const destinations = destinationRows.map(buildDestination);

  const albumSources = {
    loveTrip: "https://music.apple.com/cn/album/%E6%84%9B%E4%B9%8B%E6%97%85/905209719",
    gorgeous: "https://music.apple.com/us/album/%E8%8F%AF%E9%BA%97%E7%9A%84%E5%86%92%E9%9A%AA/818157917?l=zh-Hans-CN",
    inner: "https://music.apple.com/us/album/%E6%88%91%E5%96%9C%E6%AD%A1%E4%B8%8A%E4%BD%A0%E6%99%82%E7%9A%84%E5%85%A7%E5%BF%83%E6%B4%BB%E5%8B%95/1238560844",
    demo3: "https://music.douban.com/subject/5292091/",
    sofa: "https://music.apple.com/us/album/%E6%B2%99%E7%99%BC%E6%B5%B7/1444601920?l=zh-Hans-CN",
    havanaBook: "https://book.douban.com/subject_search?search_text=%E9%99%88%E7%BB%AE%E8%B4%9E%20%E8%83%8C%E5%AF%B9%E5%93%88%E7%93%A6%E9%82%A3",
    sun: "https://music.apple.com/us/album/%E5%A4%AA%E9%99%BD/815493324",
    guitar: "https://music.apple.com/us/album/%E5%90%89%E4%BB%96%E6%89%8B/152197399",
    pussy: "https://music.apple.com/us/album/p-y-single/815425119",
  };

  const songs = [
    {
      id: "paris-together",
      title: "一起去巴黎",
      artist: "侯湘婷",
      album: "爱之旅",
      localCover: assetCover("love-trip.jpg"),
      coverSource: source("Apple Music《爱之旅》封面", albumSources.loveTrip),
      factSource: source("Mulanci《一起去巴黎》歌词资料", "https://www.mulanci.org/lyric/sa20355/"),
      albumSource: source("Apple Music《爱之旅》", albumSources.loveTrip),
      places: ["巴黎"],
      lyric: "明年我们一起去巴黎",
      notes: "按用户校正：歌曲由侯湘婷演唱，作品归属《爱之旅》；在本原型中只作为陈绮贞词曲关联资料。",
    },
    {
      id: "travel-meaning",
      title: "旅行的意义",
      artist: "陈绮贞",
      album: "华丽的冒险",
      localCover: assetCover("gorgeous.jpg"),
      coverSource: source("Apple Music《华丽的冒险》封面", albumSources.gorgeous),
      factSource: source("Apple Music《华丽的冒险》", albumSources.gorgeous),
      albumSource: source("Apple Music《华丽的冒险》", albumSources.gorgeous),
      places: ["巴黎", "北京", "冲绳", "土耳其"],
      lyric: "你品尝了夜的巴黎 / 你踏过下雪的北京 / 你拥抱热情的岛屿",
      notes: "“你品尝了夜的巴黎”来自《旅行的意义》，收录于《华丽的冒险》。",
    },
    {
      id: "pussy",
      title: "Pussy",
      artist: "陈绮贞",
      album: "Pussy EP",
      localCover: assetCover("pussy.jpg"),
      coverSource: source("Apple Music《Pussy EP》封面", albumSources.pussy),
      factSource: source("Apple Music《Pussy EP》", albumSources.pussy),
      albumSource: source("Apple Music《Pussy EP》", albumSources.pussy),
      places: ["巴黎"],
      lyric: "EP 简介中的巴黎关联，作为地点资料补充。",
      notes: "按用户校正：Pussy 不作为地名歌词展示，只保留 EP 简介中的巴黎关联。",
    },
    {
      id: "inner-activity",
      title: "我喜欢上你时的内心活动",
      artist: "陈绮贞",
      album: "喜欢你 电影原声带",
      localCover: assetCover("inner.jpg"),
      coverSource: source("Apple Music《我喜欢上你时的内心活动》封面", albumSources.inner),
      factSource: source("Mulanci 作品页", "https://www.mulanci.org/lyric/sl61388/"),
      albumSource: source("Apple Music 单曲资料", albumSources.inner),
      places: ["上海", "日内瓦湖", "青海", "三亚", "冰岛", "希腊", "南美", "沙漠", "一号公路"],
      lyric: "上海的街道 / 你喜欢去哪 青海或三亚 / 冰岛或希腊 南美不去吗",
      notes: "封面已改为公开音乐资料中的电影原声带/单曲封面。",
    },
    {
      id: "jiufen-cafe",
      title: "九份的咖啡店",
      artist: "陈绮贞",
      album: "Demo 3",
      localCover: assetCover("Demo3.jpg"),
      coverSource: source("用户已下载 Demo 3 封面", search.local("./assets/covers/Demo3.jpg")),
      factSource: source("豆瓣音乐《Demo 3》资料", albumSources.demo3),
      albumSource: source("豆瓣音乐《Demo 3》", albumSources.demo3),
      places: ["九份"],
      lyric: "这样的午夜我坐在九份的咖啡店",
      notes: "Demo 3 稳定封面直链未取得，先用本地待核验占位，避免误用错误封面。",
    },
    {
      id: "shonan-train",
      title: "坐火车到传说中的湘南海岸",
      artist: "陈绮贞",
      album: "Demo 3",
      localCover: assetCover("Demo3.jpg"),
      coverSource: source("用户已下载 Demo 3 封面", search.local("./assets/covers/Demo3.jpg")),
      factSource: source("豆瓣音乐《Demo 3》资料", albumSources.demo3),
      albumSource: source("豆瓣音乐《Demo 3》", albumSources.demo3),
      places: ["湘南海岸"],
      lyric: "坐火车到传说中的湘南海岸",
      notes: "与 Demo 3 相关资料同源核验，封面暂不伪造。",
    },
    {
      id: "taipei-place",
      title: "台北某个地方",
      artist: "陈绮贞",
      album: "沙发海",
      localCover: assetCover("sofa.jpg"),
      coverSource: source("Apple Music《沙发海》封面", albumSources.sofa),
      factSource: source("Apple Music《沙发海》", albumSources.sofa),
      albumSource: source("Apple Music《沙发海》", albumSources.sofa),
      places: ["台北"],
      lyric: "有人在吗 台北的某个地方",
      notes: "收录为台北地点关联歌曲。",
    },
    {
      id: "havana-book",
      title: "背对哈瓦那",
      artist: "陈绮贞",
      album: "摄影集《背对哈瓦那》",
      localCover: assetCover("havana.png"),
      coverSource: source("用户已下载《背对哈瓦那》图片", search.local("./assets/covers/havana.png")),
      factSource: source("豆瓣图书公开检索", albumSources.havanaBook),
      albumSource: source("豆瓣图书公开检索", albumSources.havanaBook),
      places: ["哈瓦那"],
      lyric: "背对哈瓦那",
      notes: "按用户校正：这是陈绮贞摄影集关联，不写成歌曲专辑；封面暂无稳定直链，使用本地待核验书封占位。",
    },
    {
      id: "loser-flight",
      title: "失败者的飞翔",
      artist: "陈绮贞",
      album: "太阳",
      localCover: assetCover("sun.jpg"),
      coverSource: source("Apple Music《太阳》封面", albumSources.sun),
      factSource: source("Apple Music《太阳》", albumSources.sun),
      albumSource: source("Apple Music《太阳》", albumSources.sun),
      places: ["哈尔滨"],
      lyric: "写完于哈尔滨的一家饭店",
      notes: "作为哈尔滨创作地点关联。",
    },
    {
      id: "groupies",
      title: "Groupies 吉他手",
      artist: "陈绮贞",
      album: "吉他手",
      localCover: assetCover("guitar.jpg"),
      coverSource: source("Apple Music《吉他手》封面", albumSources.guitar),
      factSource: source("Apple Music《吉他手》", albumSources.guitar),
      albumSource: source("Apple Music《吉他手》", albumSources.guitar),
      places: ["挪威"],
      lyric: "你去挪威找鱼算账",
      notes: "收录为挪威地点关联歌曲。",
    },
    {
      id: "uk-next-week",
      title: "下个星期去英国",
      artist: "陈绮贞",
      album: "太阳",
      localCover: assetCover("sun.jpg"),
      coverSource: source("Apple Music《太阳》封面", albumSources.sun),
      factSource: source("Apple Music《太阳》", albumSources.sun),
      albumSource: source("Apple Music《太阳》", albumSources.sun),
      places: ["英国"],
      lyric: "你收了行李 下个星期要去英国",
      notes: "按用户校正：《下个星期去英国》收录于《太阳》。",
    },
  ];

  window.CHEER_TRAVEL_DATA = { destinations, songs, continents, accessed };
})();
